### PR TITLE
fix: use Threads if Pools fails

### PR DESCRIPTION
**Pull request by semoal**

### CODE REVIEW

**Comment by mara004** [comment]
No! This is illegal as per https://pypdfium2.readthedocs.io/en/stable/python_api.html#thread-incompatibility

**Comment by semoal** [comment]
> No! This is illegal as per [pypdfium2.readthedocs.io/en/stable/python_api.html#thread-incompatibility](https://pypdfium2.readthedocs.io/en/stable/python_api.html#thread-incompatibility) and is bound to cause corruption / segfaults.

> To parallelize expensive pdfium tasks such as rendering, consider processes instead of threads.

Right now, what is causing failures is the ProcessPool runing inside a celery process, fyi: https://github.com/VikParuchuri/surya/pull/182, do you know any other way of handling this better?

**Comment by mara004** [comment]
Read https://github.com/pypdfium2-team/pypdfium2/issues/309, in particular https://github.com/pypdfium2-team/pypdfium2/issues/309#issuecomment-2154519751

**Comment by semoal** [comment]
Would be interesting to remove also the PoolProcessExecutor to avoid issues with this environments then

**Comment by mara004** [comment]
This is not a pdftext issue, but a caller-side integration issue. Therefore it also needs to be fixed on the caller side. I think you are editing at the wrong place – it's quite legitimate for pdftext to use multiprocessing.

If your environment breaks multiprocessing, it's your own issue to deal with the consequences.
https://github.com/pypdfium2-team/pypdfium2/issues/309 hints that there may be options to configure celery differently.
Alternatively, if you intend to handle parallelization on the caller side through your environment, then you are perhaps using the wrong API layer.

**Pull request closed without merging**
